services:
  mysql:
    container_name: gps_db
    image: mysql:8
    volumes:
      - gps:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      backend_network:
        ipv4_address: 172.55.0.2
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: 'gps_db'
      MYSQL_USER: 'gps'
      MYSQL_PASSWORD: 'gps'
      MYSQL_ROOT_PASSWORD: 'gps_root'
  gps:
    container_name: gps_api
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    volumes:
      - type: bind
        source: ./src/
        target: /app/src/
      - type: bind
        source: ./package.json
        target: /app/package.json
      - type: bind
        source: ./tsconfig.json
        target: /app/tsconfig.json
    networks:
      backend_network:
        ipv4_address: 172.55.0.3
    depends_on:
      - mysql
    ports:
      - 3000:3000
    environment:
      PORT: '3000'
      NODE_ENV: 'local'
      DATABASE_URL: 'mysql://gps:gps@172.55.0.2:3306/gps_db?connection_limit=1'
      REGISTRATION_AUTO_LOGIN: 'true'
      PASSWORD_BCRYPT_ROUNDS: '12'
      PASSWORD_HISTORY_LIMIT: '5'
      PASSWORD_CHECK_COMPROMISED: 'true'
      REGISTER_RATE_LIMIT_ATTEMPTS: '5'
      REGISTER_RATE_LIMIT_TIMEFRAME: '300000'
volumes:
  gps:
networks:
  backend_network:
    ipam:
      driver: default
      config:
        - subnet: 172.55.0.0/16
